'use client';

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Gamepad2, Code, Clock } from "lucide-react";
import { useFlags } from "launchdarkly-react-client-sdk";

const Games = () => {
  const { "show-games": showGames } = useFlags();
  const [comingSoonOpen, setComingSoonOpen] = useState(false);

  const isGameAvailable = showGames !== false;

  const games = [
    {
      title: "Roddy's StarTrack",
      description: "Created for my nephew Roddy, this digital adaptation brings a beloved physical board game to life. Built using an AI-first development approach: parallel PRDs generated by Claude and ChatGPT, both prototyped in Lovable, with the winning version refined in VS Code and deployed via Harness CI/CD pipeline.",
      tech: ["React", "TypeScript", "AI Integration"],
      image: "/assets/startrack-preview.png",
      results: "Validated AI PRD methodology comparing Claude vs ChatGPT outputs. Established rapid prototyping pipeline using Lovable for quick iteration. Built production-ready game with comprehensive test suite via Harness.",
      process: [
        "Generated competing PRDs with Claude and ChatGPT to test AI-assisted product design",
        "Prototyped both versions simultaneously in Lovable for rapid visual iteration",
        "Selected the stronger prototype and refined game logic, animations, and board layout in VS Code",
        "Deployed with Harness CI/CD pipeline including automated testing on every push"
      ],
      badge: "AI-First Development",
      buttons: [
        { label: "Play Game", icon: Gamepad2, link: "/roddysgame", variant: "default" as const },
        { label: "View Code", icon: Code, link: "https://github.com/devonclemente/roddys-star-track-gpt", variant: "outline" as const }
      ]
    }
  ];

  return (
    <>
      <section id="games" className="py-24 bg-muted/30">
        <div className="container mx-auto px-6">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <Badge variant="secondary" className="mb-4 px-4 py-2 text-sm font-medium">Interactive Projects</Badge>
              <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
                Games &<span className="text-primary block">Interactive Projects</span>
              </h2>
              <p className="text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
                Interactive experiences built with modern web technologies. Combining creativity
                with technical skills to create engaging digital games.
              </p>
            </div>

            <div className="flex justify-center">
              {games.map((game, index) => (
                <Card key={index} className="group bg-gradient-card shadow-[0_0_30px_rgba(var(--primary-rgb),0.15)] hover:shadow-[0_0_40px_rgba(var(--primary-rgb),0.25)] transition-all duration-300 border-2 border-primary/30 overflow-hidden max-w-2xl w-full flex flex-col">
                  <div className="h-52 shrink-0 bg-gradient-to-br from-primary/10 via-muted to-primary/5 flex items-center justify-center border-b border-border/50 overflow-hidden">
                    {game.image ? (
                      <img src={game.image} alt={`${game.title} preview`} className="w-full h-full object-cover" />
                    ) : (
                      <Gamepad2 className="w-16 h-16 text-primary/40" />
                    )}
                  </div>
                  <CardHeader className="pb-4">
                    <div className="flex items-start justify-between mb-3">
                      <CardTitle className="text-lg font-semibold text-foreground leading-tight">{game.title}</CardTitle>
                      {game.badge && <Badge variant="default" className="ml-2 shrink-0">{game.badge}</Badge>}
                    </div>
                    <p className="text-muted-foreground text-sm leading-relaxed">{game.description}</p>
                  </CardHeader>
                  <CardContent className="flex flex-col h-full">
                    <div className="space-y-6 flex-grow">
                      <div>
                        <h4 className="text-sm font-medium text-foreground mb-2">Technology Stack</h4>
                        <div className="flex flex-wrap gap-2">
                          {game.tech.map((tech, i) => (
                            <Badge key={i} variant="outline" className="text-xs bg-muted/50">{tech}</Badge>
                          ))}
                        </div>
                      </div>
                      {game.results && (
                        <div className="bg-primary/5 rounded-lg p-4 border border-primary/10">
                          <h4 className="text-sm font-medium text-primary mb-1">Results</h4>
                          <p className="text-sm text-muted-foreground">{game.results}</p>
                        </div>
                      )}
                      {game.process && (
                        <div>
                          <h4 className="text-sm font-medium text-foreground mb-2">Development Process</h4>
                          <ul className="space-y-2">
                            {game.process.map((step, i) => (
                              <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                                <span className="text-primary mt-1 shrink-0">&#8226;</span>{step}
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                    <div className="flex gap-3 pt-6 mt-auto">
                      {game.buttons.map((button, i) => {
                        const Icon = button.icon;
                        const isPlayButton = button.label === "Play Game";
                        if (isPlayButton && !isGameAvailable) {
                          return (
                            <Button key={i} variant={button.variant} size="sm" className="flex-1" onClick={() => setComingSoonOpen(true)}>
                              <Icon className="w-4 h-4 mr-2" />{button.label}
                            </Button>
                          );
                        }
                        const isExternal = button.link.startsWith('http');
                        return (
                          <Button key={i} variant={button.variant} size="sm" className="flex-1" asChild>
                            <a href={button.link} {...(isExternal ? { target: "_blank", rel: "noopener noreferrer" } : {})}>
                              <Icon className="w-4 h-4 mr-2" />{button.label}
                            </a>
                          </Button>
                        );
                      })}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>

      <Dialog open={comingSoonOpen} onOpenChange={setComingSoonOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader className="text-center sm:text-center">
            <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
              <Clock className="h-6 w-6 text-primary" />
            </div>
            <DialogTitle className="text-xl">Coming Soon</DialogTitle>
            <DialogDescription className="text-base">
              Check back later for the game! We're working hard to bring you an amazing experience.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-center pt-4">
            <Button onClick={() => setComingSoonOpen(false)}>Got it</Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default Games;
